# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 738e085eb2e89087f5986e0e896e70e1a5e18cad2e5631ed99f596906d0528d99cea33bb87bdaceb1618df66943f0d5844f420f0e828ff4399ddad6ccdc5c248

test:
  secret_key_base: c774e0cf36e87c951df5c6c27f05bbabe631d781bf8afc7a52f7ea677e3d10d73d5d5ff46bc6df9b3024657bcffa514daec639cca135576d3f1c64d205b0fcb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
